# Generated by Django 6.0 on 2026-04-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('contingut', models.TextField()),
                ('imatge_url', models.URLField(blank=True, null=True)),
                ('data_publicacio', models.DateTimeField(auto_now_add=True)),
                ('font', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
