# Generated by Django 6.0 on 2026-04-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_missatge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Superadmin', 'Superadministrador'), ('Admin', 'Administrador'), ('Terapeuta', 'Terapeuta'), ('Client', 'Usuari Final o Client')], default='Client', max_length=20, verbose_name='Rol'),
        ),
    ]
